### ISSUE TITLE
argonaut-monocle issues

### ISSUE THREAD

**Issue by newhoggy** [argonaut-io/argonaut#241]
The following code doesn't compile for me:

```
  val triggersLens =
    jObjectPrism ^|-? index("attack")     ^<-?
    jObjectPrism ^|-? index("triggers")   ^<-?
    jObjectPrism ^|-? index("item")
```

I tried using my own `jObjectFieldsPrism` instead:

```
  val jObjectFieldsPrism =
    Prism[Json, Map[JsonField, Json]](
      _.fold(None,
        _ => None,
        _ => None,
        _ => None,
        _ => None,
        o => Some(o.toMap))
    )(Map.empty)
```

But that fails at runtime.

The runtime failure is:

```
java.util.NoSuchElementException: key not found: Map(...)
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at monocle.Prism$$anon$7.reverseGet(Prism.scala:292)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PLens$$anon$7$$anonfun$modify$1.apply(Lens.scala:239)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at monocle.PLens$$anon$7$$anonfun$modify$1.apply(Lens.scala:239)
  at monocle.PPrism$$anonfun$modify$1$$anonfun$apply$4.apply(Prism.scala:55)
  at scalaz.$bslash$div.fold(Either.scala:58)
  at monocle.PPrism$$anonfun$modify$1.apply(Prism.scala:55)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
  at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
```

My code is:

```
import argonaut.Argonaut._
import argonaut.JsonMonocle._
import argonaut._
import monocle._
import monocle.function.Each.each
import monocle.function.{At, Index}
import monocle.std.list._
import monocle.std.map._

val jObjectFieldsPrism =
  Prism[Json, Map[JsonField, Json]](
    _.fold(None,
      _ => None,
      _ => None,
      _ => None,
      _ => None,
      o => Some(o.toMap))
  )(Map.empty)

val triggersLens =
  jObjectFieldsPrism ^|-? index("attack")     ^<-?
  jObjectFieldsPrism ^|-? index("triggers")   ^<-?
  jObjectFieldsPrism ^|-? index("item")
```

I am using `argonaut-monocle 6.2-M3`.  The snapshot isn't resolving for me, but I prefer not to use it anyway.

**Comment by julien-truffaut** [comment]
the error comes from a call to `Map.apply` instead of a safe `Map.get`:
```
at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
```

I can't see where such a call is made

**Comment by newhoggy** [comment]
For some reason, on line `141` above, I have these variables:

![image](https://cloud.githubusercontent.com/assets/63014/16601355/6a9270d6-434f-11e6-926e-0719aa6428ba.png)

For some reason it looks like the map is empty and the key is a map containing my stuff from my source document.

This looks very wrong.

**Comment by newhoggy** [comment]
This is what the call-frame below the `AbstractMap.apply` looks like:

![image](https://cloud.githubusercontent.com/assets/63014/16601519/494716b0-4350-11e6-838f-55fde1c7867e.png)

**Comment by julien-truffaut** [comment]
I cannot reproduce your issue, here is the code I have:

```
object MonocleIssue extends App {
  import argonaut.Argonaut._
  import argonaut._
  import monocle._
  import monocle.function.Index.index
  import monocle.std.map._

  val jObjectFieldsPrism =
    Prism[Json, Map[JsonField, Json]](
      _.fold(None,
        _ => None,
        _ => None,
        _ => None,
        _ => None,
        o => Some(o.toMap))
    )(Map.empty)

  val triggersLens =
    jObjectFieldsPrism ^|-? index("attack")     ^<-?
      jObjectFieldsPrism ^|-? index("triggers")   ^<-?
      jObjectFieldsPrism ^|-? index("item")
  
  val json = Parse.parseOption(
    """
      |{
      |  "attack" : {
      |    "triggers" : {
      |      "item" : 4
      |    }
      |  }
      |}
    """.stripMargin).getOrElse(sys.error("Invalid json"))

  println(
    triggersLens.getOption(json)
  )
  
}
```

It prints Some(4)

I used the following dependencies:
```
libraryDependencies ++= Seq(
  "io.argonaut" %% "argonaut"               % "6.2-M3",
  "io.argonaut" %% "argonaut-monocle" % "6.2-M3"
)
```

**Comment by newhoggy** [comment]
Try this version:

```
object MonocleIssue extends App {
  import argonaut.Argonaut._
  import argonaut._
  import monocle._
  import monocle.function.Index.index
  import monocle.std.map._

  val jObjectFieldsPrism =
    Prism[Json, Map[JsonField, Json]](
      _.fold(None,
        _ => None,
        _ => None,
        _ => None,
        _ => None,
        o => Some(o.toMap))
    )(Map.empty)

  val triggersLens =
    jObjectFieldsPrism ^|-? index("attack")     ^<-?
        jObjectFieldsPrism ^|-? index("triggers")   ^<-?
        jObjectFieldsPrism ^|-? index("item")

  val json = Parse.parseOption(
    """
      |{
      |  "attack" : {
      |    "triggers" : {
      |      "item" : 4
      |    }
      |  }
      |}
    """.stripMargin).getOrElse(sys.error("Invalid json"))

  def asArray(j: Json) = if (j.isArray) j else jArray(List(j))

  println(triggersLens.modify(asArray).apply(json))
}
```

**Comment by julien-truffaut** [comment]
ah I missed id but your `jObjectFieldsPrism` is wrong as you set `reverseGet` to `Map.empty`. I don't know why it is not a compile error. The following is working:

```scala
val jObjectFieldsPrism =
    Prism[Json, Map[JsonField, Json]](
      _.fold(None,
        _ => None,
        _ => None,
        _ => None,
        _ => None,
        o => Some(o.toMap))
    )(m => jObject(JsonObject.fromTraversableOnce(m)))
```

**Comment by julien-truffaut** [comment]
turns out that `Map[A, B]` extends `PartialFunction[A, B]` that's why your code compiled

**Comment by seanparsons** [comment]
@julien-truffaut `PartialFunction` really is the gift that keeps on giving.

**Comment by seanparsons** [comment]
@newhoggy @julien-truffaut Can this be closed?

**Comment by newhoggy** [comment]
Yes please.  Thanks so much for your help!
